
[build]
  command = "npm run build:all"
  functions = "./build/functions/"
  publish = "./build/deploy/"

  [functions]
  included_files = ["./build/functions/**"]

  [[redirects]]
    from = "/*"
    to = "/openapi.json"
    status = 200